spring.application.name=neocare_followUp
# ======================
# DATABASE CONFIG MYSQL
# ======================
spring.datasource.url=jdbc:mysql://localhost:3306/neocare_db?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

# ======================
# JPA / HIBERNATE
# ======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ======================
# SERVER
# ======================
server.port=8080


